CREATE TABLE OACX_ADMIN (
  ID VARCHAR(60) NOT NULL COMMENT '로그인 아이디',
  NAME VARCHAR(16) DEFAULT NULL COMMENT '사용자명',
  PASSWD VARCHAR(64) DEFAULT NULL COMMENT '비밀번호(HASH)',
  SEED VARCHAR(10) DEFAULT NULL COMMENT '알고리즘 블록암호',
  PASSWD_CHANGE_DATE DATETIME DEFAULT NULL COMMENT '비밀번호 변경일자',
  STATE_CODE VARCHAR(40) DEFAULT NULL COMMENT '상태코드',
  AUTHORITY_CODE VARCHAR(40) DEFAULT NULL COMMENT '권한코드',
  DEPT_NAME VARCHAR(40) DEFAULT NULL COMMENT '부서명',
  PHONE_NO VARCHAR(14) DEFAULT NULL COMMENT '전화번호',
  FAIL_CNT INT DEFAULT 0 COMMENT '로그인 실패 카운트',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최초 등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최근 수정자',
  PRIMARY KEY (ID)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='관리자 정보';

CREATE TABLE OACX_ADMIN_LAST_LOGIN (
  ID VARCHAR(50) NOT NULL COMMENT 'login id',
  LAST_LOGIN DATETIME DEFAULT NULL COMMENT 'login date'
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='관리자 마지막 로그인 정보';

CREATE TABLE OACX_AUTHENTICATE (
  REQ_TX_ID VARCHAR(40) NOT NULL COMMENT '인증요청 TX ID',
  CERT_TX_ID VARCHAR(128) DEFAULT NULL COMMENT '인증사업자 TX ID',
  PROVIDER_ID VARCHAR(20) DEFAULT NULL COMMENT '인증사업자 ID',
  PROVIDER_VERSION VARCHAR(10) DEFAULT NULL COMMENT '인증사업자 서비스 버전',
  SERVICE_TYPE VARCHAR(10) DEFAULT NULL COMMENT '요청 유형',
  STATUS_CODE VARCHAR(2) DEFAULT NULL COMMENT '진행상태코드',
  RESULT_CODE VARCHAR(10) DEFAULT NULL COMMENT '결과코드',
  PROVIDER_RESULT_CODE VARCHAR(10) DEFAULT NULL COMMENT '인증사업자 결과 코드',
  SYSTEM_MESSAGE VARCHAR(1000) DEFAULT NULL COMMENT '시스템 메세지',
  CLIENT_MESSAGE VARCHAR(4000) DEFAULT NULL COMMENT '클라이언트 메세지',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '응답일시',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '요청일시',
  USER_HASH VARCHAR(44) DEFAULT NULL COMMENT '사용자명+전화번호',
  APP_CODE CHAR(3) DEFAULT '001' COMMENT '기관별 업무',
  CALL_HISTORY VARCHAR(100) DEFAULT NULL COMMENT '호출 이력',
  SERVICE_ID VARCHAR(200) DEFAULT '100' COMMENT '서비스 아이디',
  AUTH_TYPE VARCHAR(10) COMMENT '__인증타입',
  METHOD VARCHAR(20) COMMENT '__인증매체',
  TASK_CODE VARCHAR(20) DEFAULT 'SAMPLE' COMMENT '업무코드',
  PRIMARY KEY (REQ_TX_ID)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='인증 이력 상세';


CREATE TABLE OACX_CALCULATIONS (
  SEQ INT NOT NULL AUTO_INCREMENT COMMENT 'seq',
  RGST_DATE DATE NOT NULL COMMENT '일자',
  USE_TASK_ID VARCHAR(100) NOT NULL COMMENT '사용처',
  PROVIDER_ID VARCHAR(100) NOT NULL COMMENT '인증사업자 코드',
  RQST_CNT INT DEFAULT NULL COMMENT '요청건수',
  SUCCESS_CNT INT DEFAULT NULL COMMENT '성공건수',
  FAIL_CNT INT DEFAULT NULL COMMENT '실패건수',
  CHARGE_CNT INT DEFAULT NULL COMMENT '청구건수',
  IMPERFECT_CNT INT DEFAULT NULL COMMENT '미완료건수',
  CHARGE_DATE DATETIME DEFAULT NULL COMMENT '청구건수 갱신일시',
  SERVICE_ID VARCHAR(200) DEFAULT '100' COMMENT '서비스 아이디',
  AUTH_TYPE VARCHAR(10) COMMENT '__인증타입',
  METHOD VARCHAR(20) COMMENT '__인증매체',
  TASK_CODE VARCHAR(20) DEFAULT 'SYSTEM' COMMENT '__업무코드',
  CERT_COST INT DEFAULT 0 COMMENT '__인증원가',
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='인증 이력 통계';

CREATE TABLE OACX_CHANNEL (
  CHANNEL_ID VARCHAR(16) NOT NULL COMMENT '채널 ID',
  CHANNEL_NAME VARCHAR(100) NOT NULL COMMENT '채널 명',
  USE_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(60) COMMENT '최초등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(60) COMMENT '최근수정자',
  PRIMARY KEY (CHANNEL_ID)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='채널관리';

CREATE TABLE OACX_PROVIDER (
  ID VARCHAR(100) NOT NULL COMMENT 'ID(관리자페이지 등록ID)',
  PROVIDER_ID VARCHAR(20) DEFAULT NULL COMMENT '인증사업자 ID',
  NAME VARCHAR(100) DEFAULT NULL COMMENT '인증사업자명',
  CONFIG VARCHAR(512) DEFAULT NULL COMMENT 'RESPONSE JSON',
  URL VARCHAR(500) DEFAULT NULL COMMENT 'BASE URL',
  PROVIDER_TYPE VARCHAR(20) DEFAULT NULL COMMENT '구분(공공; 민간)',
  OPER_SORT VARCHAR(20) DEFAULT NULL COMMENT '운영방식',
  STATUS_CODE CHAR(1) DEFAULT NULL COMMENT '상태코드',
  UNUSE_STYLE VARCHAR(20) DEFAULT NULL COMMENT '미사용 숨김처리 방식',
  DESCRIPTION VARCHAR(1000) DEFAULT NULL COMMENT '비고',
  PROVIDER_IF VARCHAR(3000) DEFAULT NULL COMMENT '사업자정보-JSON',
  PROVIDER_IF2 VARCHAR(2000) DEFAULT NULL COMMENT '사업자정보-JSON(예비)',
  SERVICE_TYPE VARCHAR(40) DEFAULT NULL COMMENT '웹; 앱 서비스 종류',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최초 등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최근 수정자',
  VERSION VARCHAR(10) DEFAULT NULL COMMENT '인증사업자 서비스 버전',
  CERT_COST DECIMAL(10,0) DEFAULT 0 COMMENT '__인증원가',
  UPPER_ID VARCHAR(20) DEFAULT NULL COMMENT '__상위ID',
  TREE_LEVEL VARCHAR(10) DEFAULT NULL COMMENT '__트리레벨',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='인증사업자 정보';

CREATE TABLE OACX_SERVICE (
  SERVICE_ID VARCHAR(200) NOT NULL COMMENT '서비스 아이디',
  SERVICE_NAME VARCHAR(100) NOT NULL COMMENT '서비스 명',
  STATE_CODE CHAR(1) NOT NULL COMMENT '상태코드',
  CREATE_DATE DATETIME NOT NULL COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(60) NOT NULL COMMENT '최초 등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최근 수정자',
  SERVICE_ID_AUTO_YN CHAR(1) DEFAULT NULL COMMENT '서비스 아이디 자동 생성 여부(Y/N)',
  SERVICE_CATEGORY VARCHAR(100) DEFAULT '["OACX","KEYSHARP","YESSIGN","CIVS","PIN","CELLPHONE"]' COMMENT '서비스별 사용 카테고리',
  TASK_CODE VARCHAR(20) DEFAULT NULL COMMENT '__업무코드',
  CHANNEL_ID VARCHAR(16) DEFAULT NULL COMMENT '__채널ID',
  AGREEMENT TEXT NULL DEFAULT '{"policy1": {"val": ["(주)(이하 “회사”)은 간편인증서비스 제공을 위하여 개인정보를 이용 하고자 합니다.", "- 전자금융거래 이용시 본인의 확인", "- 성명, 생년월일, 휴대폰번호", "- 수집,이용 동의일로부터 개인(신용)정보의 수집,이용 목적을 달성할 때까지 다만, 아래의 경우는 제외<br/> - 법령에서 정하는 경우 해당 기간까지 보유", "- 이용자는 회사의 개인정보 수집 및 이용 동의를 거부할 수 있습니다. 단, 동의를 거부하는 경우 간편인증서비스가 제한됩니다."]}, "policy3": {"val": ["(주)(이하 “회사”)는 간편인증서비스 제공을 위하여 인증기관에 다음의 정보를 제공하고자 합니다.", "- 로그인 및 업무처리 시 본인여부 확인", "- 카카오, 네이버, 토스, PASS", "- 성명, 생년월일, 휴대폰번호", "- 본인인증 또는 전자서명 후 즉시 파기", "이용자는 회사에서 요구하는 개인정보 제공에 대한 동의를 거부할 수 있습니다. 단, 동의를 거부하는 경우 간편인증서비스를 이용할 수 없습니다."]}}', -- 서비스별 이용약관
  PRIMARY KEY (SERVICE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서비스 관리';

CREATE TABLE OACX_SERVICE_PROVIDER (
  SERVICE_ID VARCHAR(200) NOT NULL COMMENT '서비스ID',
  PROVIDER_ID VARCHAR(20) NOT NULL COMMENT '인증사업자ID',
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최초등록자ID',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최근수정자ID',
  PROVIDER_IF varchar(3000) NULL DEFAULT NULL, 
	ACTIVE varchar(1) NOT NULL DEFAULT 'N', 
  PRIMARY KEY (SERVICE_ID, PROVIDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서비스 인증사업자 정보';


CREATE TABLE OACX_SERVICE_USER (
  SERVICE_ID VARCHAR(200) NOT NULL COMMENT '서비스 아이디',
  USER_ID VARCHAR(16) NOT NULL COMMENT '서비스 사용자 아이디',
  PRIMARY KEY (SERVICE_ID, USER_ID),
  CONSTRAINT FK_OACX_SERVICE_USER_SERVICE
    FOREIGN KEY (SERVICE_ID) REFERENCES OACX_SERVICE (SERVICE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_OACX_SERVICE_USER_ADMIN
    FOREIGN KEY (USER_ID) REFERENCES OACX_ADMIN (ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='서비스 사용자 관리';


CREATE TABLE OACX_TEMP_TOKEN (
  TX_ID VARCHAR(40) NOT NULL COMMENT '결과요청 TX_ID',
  TOKEN MEDIUMTEXT DEFAULT NULL COMMENT '암호화토큰',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '토큰 발급 일시',
  PRIMARY KEY (TX_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='연동 임시토큰 저장';


CREATE TABLE OACX_TEST_USER (
  ID INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  NAME VARCHAR(100) DEFAULT NULL COMMENT '성명',
  BIRTH_DATE VARCHAR(8) DEFAULT NULL COMMENT '생년월일 8자리',
  PHONE_NO VARCHAR(100) DEFAULT NULL COMMENT '휴대폰번호',
  PRESS_AGENCY VARCHAR(20) DEFAULT NULL COMMENT '통신사',
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(60) DEFAULT NULL COMMENT '최초등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(100) DEFAULT NULL COMMENT '최근수정자',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='대표테스트사용자';


CREATE TABLE OACX_TRANSACTION (
  ID VARCHAR(40) NOT NULL COMMENT '발급 TX ID',
  IP VARCHAR(20) DEFAULT NULL COMMENT '발급 요청 IP',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '발급일자',
  STATUS VARCHAR(2) DEFAULT NULL COMMENT '상태',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '수정일자',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='트랜잭션ID 이력';

CREATE TABLE OACX_USE_ORG (
  USE_ORG_CODE VARCHAR(100) NOT NULL COMMENT '로그인 아이디',
  USE_ORG_NAME VARCHAR(100) DEFAULT NULL COMMENT '이용기관명',
  TASK_CNT INT DEFAULT NULL COMMENT '사용업무 수',
  TASK_INFO VARCHAR(1000) DEFAULT NULL COMMENT '사용업무 정보(JSON)',
  DOMAIN_INFO VARCHAR(1000) DEFAULT NULL COMMENT '도메인정보(JSON)',
  LICENSE VARCHAR(2000) DEFAULT NULL COMMENT '라이선스 정보(JSON)',
  DESCRIPTION VARCHAR(1000) DEFAULT NULL COMMENT '비고',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(16) DEFAULT NULL COMMENT '최초 등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(16) DEFAULT NULL COMMENT '최근 수정자',
  PRIMARY KEY (USE_ORG_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='이용기관 정보';

CREATE TABLE OACX_WORKBOARD (
  BOARD_ID INT NOT NULL COMMENT '게시물 아이디',
  TITLE VARCHAR(100) DEFAULT NULL COMMENT '제목',
  CONTENT VARCHAR(1000) DEFAULT NULL COMMENT '내용',
  CREATE_DATE DATETIME DEFAULT NULL COMMENT '최초등록일자',
  CREATE_USER_ID VARCHAR(16) DEFAULT NULL COMMENT '최초 등록자',
  UPDATE_DATE DATETIME DEFAULT NULL COMMENT '최근수정일자',
  UPDATE_USER_ID VARCHAR(16) DEFAULT NULL COMMENT '최근 수정자',
  PRIMARY KEY (BOARD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='게시물 정보';
