-- ZKP 기능 사용 시 DB에 저장된 검증 데이터를 사용하기에 아래 검증타입에 대한 데이터를 저장해야합니다.
-- 각 검증 조합은 API 연동 가이드 내 "부록 정의된 ZKP 검증 종류"를 참고하세요.

-----------------------------------------------------------------------------------------------------------------------
-- 기존 ZKP 테이블 내 데이터 전체 삭제가 필요할 경우
-- DELETE FROM VF_ZKP; 
-- ※ MS-SQL DBMS의 경우 맨 앞 ID 값을 제외해야합니다. ex) INSERT INTO VF_ZKP (VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES('A_1_1', 'mdlschema', 'zkpaddr', null, null);


INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(1, 'A_1_1', 'mdlschema', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(2, 'A_1_2', 'mdlschema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(3, 'A_1_3', 'mdlschema', null,'[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(4, 'A_1_4', 'mdlschema', 'zkpasort', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(5, 'A_2_1', 'mdlschema', 'zkpaddr,zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(6, 'A_2_2', 'mdlschema', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(7, 'A_2_3', 'mdlschema', 'zkpaddr, zkpasort', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(8, 'A_2_4', 'mdlschema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(9, 'A_2_5', 'mdlschema', 'zkpsex, zkpasort', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(10, 'A_2_6', 'mdlschema', 'zkpasort', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(11, 'A_3_1', 'mdlschema', 'zkpaddr, zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(12, 'A_3_2', 'mdlschema', 'zkpaddr, zkpsex, zkpasort', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(13, 'A_3_3', 'mdlschema', 'zkpaddr, zkpasort', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(14, 'A_3_4', 'mdlschema', 'zkpsex, zkpasort', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(15, 'A_4_1', 'mdlschema', 'zkpaddr, zkpsex, zkpasort', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(16, 'B_1_1', 'mnh', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(17, 'B_1_2', 'mnh', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(18, 'B_1_3', 'mnh', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(19, 'B_1_4', 'mnh', 'zkphonlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(20, 'B_2_1', 'mnh', 'zkpaddr, zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(21, 'B_2_2', 'mnh', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(22, 'B_2_3', 'mnh', 'zkpaddr, zkphonlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(23, 'B_2_4', 'mnh', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(24, 'B_2_5', 'mnh', 'zkpsex, zkphonlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(25, 'B_2_6', 'mnh', 'zkphonlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(26, 'B_3_1', 'mnh', 'zkpaddr, zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(27, 'B_3_2', 'mnh', 'zkpaddr, zkpsex, zkphonlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(28, 'B_3_3', 'mnh', 'zkpaddr, zkphonlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(29, 'B_3_4', 'mnh', 'zkpsex, zkphonlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(30, 'B_4_1', 'mnh', 'zkpaddr, zkpsex, zkphonlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(31, 'C_1_1', 'mep', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(32, 'C_1_2', 'mep', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(33, 'C_1_3', 'mep', 'zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(34, 'C_2_1', 'mep', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(35, 'C_2_2', 'mep', 'zkpsex, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(36, 'C_2_3', 'mep', 'zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(37, 'C_3_1', 'mep', 'zkpsex, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(38, 'D_1_1', 'mrcshema', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(39, 'D_1_2', 'mrcshema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(40, 'D_1_3', 'mrcshema', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(41, 'D_1_4', 'mrcshema', 'zkpyear', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(42, 'D_2_1', 'mrcshema', 'zkpaddr, zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(43, 'D_2_2', 'mrcshema', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(44, 'D_2_3', 'mrcshema', 'zkpaddr, zkpyear', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(45, 'D_2_4', 'mrcshema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(46, 'D_2_5', 'mrcshema', 'zkpsex, zkpyear', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(47, 'D_2_6', 'mrcshema', 'zkpyear', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(48, 'D_3_1', 'mrcshema', 'zkpaddr, zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(49, 'D_3_2', 'mrcshema', 'zkpaddr, zkpsex, zkpyear', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(50, 'D_3_3', 'mrcshema', 'zkpaddr, zkpyear', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(51, 'D_3_4', 'mrcshema', 'zkpsex, zkpyear', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(52, 'D_4_1', 'mrcshema', 'zkpaddr, zkpsex, zkpyear', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(53, 'E_1_1', 'mfc', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(54, 'E_1_2', 'mfc', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(55, 'E_1_3', 'mfc', null, null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(56, 'E_1_4', 'mfc', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(57, 'E_1_5', 'mfc', 'zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(58, 'E_1_6', 'mfc', 'zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(59, 'E_2_1', 'mfc', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(60, 'E_2_2', 'mfc', 'zkpsex, zkpyear', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(61, 'E_2_3', 'mfc', 'zkpsex, zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(62, 'E_2_4', 'mfc', 'zkpsex, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(63, 'E_2_5', 'mfc', 'zkpsex, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(64, 'E_2_6', 'mfc', 'zkpyear', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(65, 'E_2_7', 'mfc', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(66, 'E_2_8', 'mfc', 'zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(67, 'E_2_9', 'mfc', 'zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(68, 'E_2_10', 'mfc', 'zkpyear, zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(69, 'E_2_11', 'mfc', 'zkpyear, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(70, 'E_2_12', 'mfc', 'zkpyear, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(71, 'E_2_13', 'mfc', 'zkpaddr, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(72, 'E_2_14', 'mfc', 'zkpaddr, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(73, 'E_2_15', 'mfc', 'zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(74, 'E_3_1', 'mfc', 'zkpsex, zkpyear', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(75, 'E_3_2', 'mfc', 'zkpsex, zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(76, 'E_3_3', 'mfc', 'zkpsex, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(77, 'E_3_4', 'mfc', 'zkpsex, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(78, 'E_3_5', 'mfc', 'zkpsex, zkpyear, zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(79, 'E_3_6', 'mfc', 'zkpsex, zkpyear, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(80, 'E_3_7', 'mfc', 'zkpsex, zkpyear, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(81, 'E_3_8', 'mfc', 'zkpsex, zkpaddr, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(82, 'E_3_9', 'mfc', 'zkpsex, zkpaddr, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(83, 'E_3_10', 'mfc', 'zkpsex, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(84, 'E_3_11', 'mfc', 'zkpyear, zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(85, 'E_3_12', 'mfc', 'zkpyear, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(86, 'E_3_13', 'mfc', 'zkpyear, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(87, 'E_3_14', 'mfc', 'zkpaddr, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(88, 'E_3_15', 'mfc', 'zkpaddr, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(89, 'E_3_16', 'mfc', 'zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(90, 'E_3_17', 'mfc', 'zkpyear, zkpaddr, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(91, 'E_3_18', 'mfc', 'zkpyear, zkpaddr, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(92, 'E_3_19', 'mfc', 'zkpyear, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(93, 'E_3_20', 'mfc', 'zkpaddr, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(94, 'E_4_1', 'mfc', 'zkpsex, zkpyear, zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(95, 'E_4_2', 'mfc', 'zkpsex, zkpyear, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(96, 'E_4_3', 'mfc', 'zkpsex, zkpyear, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(97, 'E_4_4', 'mfc', 'zkpsex, zkpaddr, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(98, 'E_4_5', 'mfc', 'zkpsex, zkpaddr, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(99, 'E_4_6', 'mfc', 'zkpsex, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(100, 'E_4_7', 'mfc', 'zkpsex, zkpyear, zkpaddr, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(101, 'E_4_8', 'mfc', 'zkpsex, zkpyear, zkpaddr, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(102, 'E_4_9', 'mfc', 'zkpsex, zkpyear, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(103, 'E_4_10', 'mfc', 'zkpsex, zkpaddr, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(104, 'E_4_11', 'mfc', 'zkpyear, zkpaddr, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(105, 'E_4_12', 'mfc', 'zkpyear, zkpaddr, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(106, 'E_4_13', 'mfc', 'zkpyear, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(107, 'E_4_14', 'mfc', 'zkpaddr, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(108, 'E_4_15', 'mfc', 'zkpyear, zkpaddr, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(109, 'E_5_1', 'mfc', 'zkpsex, zkpyear, zkpaddr, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(110, 'E_5_2', 'mfc', 'zkpsex, zkpyear, zkpaddr, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(111, 'E_5_3', 'mfc', 'zkpsex, zkpyear, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(112, 'E_5_4', 'mfc', 'zkpsex, zkpaddr, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(113, 'E_5_5', 'mfc', 'zkpsex, zkpyear, zkpaddr, zkpnationality, zkpqualstay', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(114, 'E_5_6', 'mfc', 'zkpyear, zkpaddr, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(115, 'E_6_1', 'mfc', 'zkpsex, zkpyear, zkpaddr, zkpnationality, zkpqualstay', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(116, 'F_1_1', 'mdlschema,mnh,mep,mrcshema,mfc,mdcshema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(117, 'F_1_2', 'mdlschema,mnh,mep,mrcshema,mfc,mdcshema', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(118, 'F_2_1', 'mdlschema,mnh,mep,mrcshema,mfc,mdcshema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(119, 'G_1_1', 'mdlschema,mnh,mrcshema,mfc,mdcshema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(120, 'G_1_2', 'mdlschema,mnh,mrcshema,mfc,mdcshema', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(121, 'G_1_3', 'mdlschema,mnh,mrcshema,mfc,mdcshema', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(122, 'G_2_1', 'mdlschema,mnh,mrcshema,mfc,mdcshema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(123, 'G_2_2', 'mdlschema,mnh,mrcshema,mfc,mdcshema', 'zkpsex, zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(124, 'G_2_3', 'mdlschema,mnh,mrcshema,mfc,mdcshema', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(125, 'G_3_1', 'mdlschema,mnh,mrcshema,mfc,mdcshema', 'zkpsex, zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(126, 'H_1_1', 'mdlschema,mnh,mrcshema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(127, 'H_1_2', 'mdlschema,mnh,mrcshema', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(128, 'H_1_3', 'mdlschema,mnh,mrcshema', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(129, 'H_2_1', 'mdlschema,mnh,mrcshema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(130, 'H_2_2', 'mdlschema,mnh,mrcshema', 'zkpsex, zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(131, 'H_2_3', 'mdlschema,mnh,mrcshema', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(132, 'H_3_1', 'mdlschema,mnh,mrcshema', 'zkpsex, zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(133, 'I_1_1', 'mdlschema,mrcshema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(134, 'I_1_2', 'mdlschema,mrcshema', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(135, 'I_1_3', 'mdlschema,mrcshema', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(136, 'I_2_1', 'mdlschema,mrcshema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(137, 'I_2_2', 'mdlschema,mrcshema', 'zkpsex, zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(138, 'I_2_3', 'mdlschema,mrcshema', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(139, 'I_3_1', 'mdlschema,mrcshema', 'zkpsex, zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(140, 'J_1_1', 'mep,mfc', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(141, 'J_1_2', 'mep,mfc', null, '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(142, 'J_1_3', 'mep,mfc', 'zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(143, 'J_2_1', 'mep,mfc', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(144, 'J_2_2', 'mep,mfc', 'zkpsex, zkpnationality', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(145, 'J_2_3', 'mep,mfc', 'zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(146, 'J_3_1', 'mep,mfc', 'zkpsex, zkpnationality', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(147, 'K_1_1', 'mdcshema', 'zkpaddr', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(148, 'K_1_2', 'mdcshema', 'zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(149, 'K_1_3', 'mdcshema', null,'[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(150, 'K_1_4', 'mdcshema', 'zkphndyn', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(151, 'K_1_5', 'mdcshema', 'zkphndlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(152, 'K_1_6', 'mdcshema', 'zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(153, 'K_2_1', 'mdcshema', 'zkpaddr, zkpsex', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(154, 'K_2_2', 'mdcshema', 'zkpaddr', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(155, 'K_2_3', 'mdcshema', 'zkpaddr, zkphndyn', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(156, 'K_2_4', 'mdcshema', 'zkpaddr, zkphndlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(157, 'K_2_5', 'mdcshema', 'zkpaddr, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(158, 'K_2_6', 'mdcshema', 'zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(159, 'K_2_7', 'mdcshema', 'zkpsex, zkphndyn', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(160, 'K_2_8', 'mdcshema', 'zkpsex, zkphndlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(161, 'K_2_9', 'mdcshema', 'zkpsex, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(162, 'K_2_10', 'mdcshema', 'zkphndyn', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(163, 'K_2_11', 'mdcshema', 'zkphndyn, zkphndlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(164, 'K_2_12', 'mdcshema', 'zkphndyn, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(165, 'K_2_13', 'mdcshema', 'zkphndlist, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(166, 'K_2_14', 'mdcshema', 'zkphndlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(167, 'K_2_15', 'mdcshema', 'zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(168, 'K_3_1', 'mdcshema', 'zkpaddr, zkpsex', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(169, 'K_3_2', 'mdcshema', 'zkpaddr, zkpsex, zkphndyn', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(170, 'K_3_3', 'mdcshema', 'zkpaddr, zkpsex, zkphndlist', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(171, 'K_3_4', 'mdcshema', 'zkpaddr, zkpsex, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(172, 'K_3_5', 'mdcshema', 'zkpaddr, zkphndyn', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(173, 'K_3_6', 'mdcshema', 'zkpaddr, zkphndlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(174, 'K_3_7', 'mdcshema', 'zkpaddr, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(175, 'K_3_8', 'mdcshema', 'zkpaddr, zkphndyn, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(176, 'K_3_9', 'mdcshema', 'zkpsex, zkphndyn', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(177, 'K_3_10', 'mdcshema', 'zkpsex, zkphndlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(178, 'K_3_11', 'mdcshema', 'zkpsex, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(179, 'K_3_12', 'mdcshema', 'zkpsex, zkphndlist, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(180, 'K_3_13', 'mdcshema', 'zkphndyn, zkphndlist, zkpwalkdisinfo', null, null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(181, 'K_4_1', 'mdcshema', 'zkpaddr, zkpsex, zkphndyn', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(182, 'K_4_2', 'mdcshema', 'zkpaddr, zkpsex, zkphndlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(183, 'K_4_3', 'mdcshema', 'zkpaddr, zkpsex, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(184, 'K_4_4', 'mdcshema', 'zkpsex, zkphndyn, zkphndlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(185, 'K_4_5', 'mdcshema', 'zkpsex, zkphndyn, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(186, 'K_4_6', 'mdcshema', 'zkphndyn, zkphndlist, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(187, 'K_5_1', 'mdcshema', 'zkpaddr, zkpsex, zkphndyn, zkphndlist', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(188, 'K_5_2', 'mdcshema', 'zkpaddr, zkpsex, zkphndyn, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(189, 'K_5_3', 'mdcshema', 'zkpsex, zkphndyn, zkphndlist, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);
INSERT INTO VF_ZKP (ID, VERIFY_TYPE, SCHEMA_NAME, ATTRIBUTES, PREDICATES, CREATED_AT) VALUES(190, 'K_6_1', 'mdcshema', 'zkpaddr, zkpsex, zkphndyn, zkphndlist, zkpwalkdisinfo', '[{"zkpbirth":{"type":"LE","value":"-19"}}]', null);