CREATE TABLE `OACX_ADMIN` (
  `ID` varchar(16) NOT NULL COMMENT '로그인 아이디',
  `NAME` varchar(16) DEFAULT NULL COMMENT '사용자명',
  `PASSWD` varchar(64) DEFAULT NULL COMMENT '비밀번호(HASH)',
  `SEED` varchar(10) DEFAULT NULL COMMENT '알고리즘 블록암호',
  `PASSWD_CHANGE_DATE` datetime DEFAULT NULL COMMENT '비밀번호 변경일자',
  `STATE_CODE` varchar(40) DEFAULT NULL COMMENT '상태코드',
  `AUTHORITY_CODE` varchar(40) DEFAULT NULL COMMENT '권한코드',
  `DEPT_NAME` varchar(40) DEFAULT NULL COMMENT '부서명',
  `PHONE_NO` varchar(14) DEFAULT NULL COMMENT '전화번호',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '최초등록일자',
  `CREATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최초 등록자',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '최근수정일자',
  `UPDATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최근 수정자',
  `FAIL_CNT` int DEFAULT 0 COMMENT '로그인 실패 횟수',
  `FAIL_HIST` datetime DEFAULT NULL COMMENT '로그인 잠금 시간',
  PRIMARY KEY (`ID`)
) COMMENT='관리자 정보';

CREATE TABLE `OACX_AUTHENTICATE` (
  `REQ_TX_ID` varchar(40) NOT NULL COMMENT '인증요청 TX ID',
  `CERT_TX_ID` varchar(128) DEFAULT NULL COMMENT '인증사업자 TX ID',
  `PROVIDER_ID` varchar(20) DEFAULT NULL,
  `PROVIDER_VERSION` varchar(10) DEFAULT NULL,
  `SERVICE_TYPE` varchar(10) DEFAULT NULL COMMENT '요청 유형',
  `STATUS_CODE` varchar(2) DEFAULT NULL COMMENT '진행상태코드',
  `RESULT_CODE` varchar(10) DEFAULT NULL COMMENT '결과코드',
  `PROVIDER_RESULT_CODE` varchar(10) DEFAULT NULL,
  `SYSTEM_MESSAGE` varchar(1000) DEFAULT NULL COMMENT '시스템 메세지',
  `CLIENT_MESSAGE` varchar(4000) DEFAULT NULL COMMENT '클라이언트 메세지',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '응답일시',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '요청일시',
  `USER_HASH` varchar(44) DEFAULT NULL COMMENT '사용자명+전화번호',
  `APP_CODE` char(3) DEFAULT '001' COMMENT '기관별업무?',
  `CALL_HISTORY` varchar(100) DEFAULT NULL COMMENT '호출 이력',
  `SERVICE_ID` varchar(200) NOT NULL DEFAULT '100' COMMENT '서비스 아이디',
  PRIMARY KEY (`REQ_TX_ID`)
) COMMENT='인증 이력 상세';

CREATE TABLE `OACX_CALCULATIONS` (
  `RGST_DATE` date NOT NULL COMMENT '일자',
  `USE_TASK_ID` varchar(100) NOT NULL COMMENT '사용처',
  `PROVIDER_ID` varchar(100) NOT NULL COMMENT '인증사업자 코드',
  `RQST_CNT` int(11) DEFAULT NULL COMMENT '요청건수',
  `SUCCESS_CNT` int(11) DEFAULT NULL COMMENT '성공건수',
  `FAIL_CNT` int(11) DEFAULT NULL COMMENT '실패건수',
  `CHARGE_CNT` int(11) DEFAULT NULL COMMENT '청구건수',
  `IMPERFECT_CNT` int(11) DEFAULT NULL COMMENT '미완료건수',
  `CHARGE_DATE` datetime DEFAULT NULL COMMENT '청구건수 갱신일시',
  `SERVICE_ID` varchar(200) DEFAULT '100' COMMENT '서비스 아이디',
  PRIMARY KEY (`RGST_DATE`,`USE_TASK_ID`,`PROVIDER_ID`, `SERVICE_ID`)
) COMMENT='인증 이력 통계';

CREATE TABLE `OACX_PROVIDER` (
  `ID` varchar(100) NOT NULL COMMENT 'ID(관리자페이지 등록ID)',
  `PROVIDER_ID` varchar(25) DEFAULT NULL COMMENT '인증사업자 ID',
  `NAME` varchar(100) DEFAULT NULL COMMENT '인증사업자명',
  `CONFIG` varchar(512) DEFAULT NULL COMMENT 'RESPONSE JSON',
  `URL` varchar(500) DEFAULT NULL COMMENT 'BASE URL',
  `PROVIDER_TYPE` varchar(20) DEFAULT NULL COMMENT '구분(공공, 민간)',
  `OPER_SORT` varchar(20) DEFAULT NULL COMMENT '운영방식',
  `STATUS_CODE` char(1) DEFAULT NULL COMMENT '상태코드',
  `UNUSE_STYLE` varchar(20) DEFAULT NULL COMMENT '미사용 숨김처리 방식',
  `DESCRIPTION` varchar(1000) DEFAULT NULL COMMENT '비고',
  `PROVIDER_IF` varchar(2000) DEFAULT NULL COMMENT '사업자정보-JSON',
  `PROVIDER_IF2` varchar(2000) DEFAULT NULL COMMENT '사업자정보-JSON(예비)',
  `SERVICE_TYPE` varchar(40) DEFAULT NULL COMMENT '웹, 앱 서비스 종류',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '최초등록일자',
  `CREATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최초 등록자',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '최근수정일자',
  `UPDATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최근 수정자',
  `VERSION` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) COMMENT='인증사업자 정보';

CREATE TABLE `OACX_SERVICE` (
  `SERVICE_ID` varchar(200) NOT NULL COMMENT '서비스 아이디',
  `SERVICE_NAME` varchar(100) NOT NULL COMMENT '서비스 명',
  `STATE_CODE` char(1) NOT NULL COMMENT '사용 여부',
  `CREATE_DATE` datetime NOT NULL COMMENT '생성일시',
  `CREATE_USER_ID` varchar(16) NOT NULL COMMENT '생성자 아이디',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '수정일시',
  `UPDATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '수정자 아이디',
  `SERVICE_ID_AUTO_YN` char(1) DEFAULT NULL COMMENT '서비스 아이디 자동 생성 여부(Y/N)',
  PRIMARY KEY (`SERVICE_ID`)
) COMMENT='서비스 관리';

CREATE TABLE `OACX_SERVICE_USER` (
  `SERVICE_ID` varchar(200) NOT NULL COMMENT '서비스 아이디',
  `USER_ID` varchar(16) NOT NULL COMMENT '서비스 사용자 아이디',
  PRIMARY KEY (`SERVICE_ID`,`USER_ID`),
  KEY `OACX_SERVICE_USER_FK` (`USER_ID`),
  CONSTRAINT `OACX_SERVICE_USER_FK` FOREIGN KEY (`USER_ID`) REFERENCES `OACX_ADMIN` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `OACX_SERVICE_USER_FK_1` FOREIGN KEY (`SERVICE_ID`) REFERENCES `OACX_SERVICE` (`SERVICE_ID`) ON DELETE CASCADE
) COMMENT='서비스 사용자 관리';

CREATE TABLE `OACX_TRANSACTION` (
  `ID` varchar(40) NOT NULL COMMENT '발급 TX ID',
  `IP` varchar(20) DEFAULT NULL COMMENT '발급 요청 IP',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '발급일자',
  `STATUS` varchar(2) DEFAULT NULL,
  `UPDATE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) COMMENT='트랜잭션ID 이력';

CREATE TABLE `OACX_USE_ORG` (
  `USE_ORG_CODE` varchar(100) NOT NULL COMMENT '로그인 아이디',
  `USE_ORG_NAME` varchar(100) DEFAULT NULL COMMENT '이용기관명',
  `TASK_CNT` int(11) DEFAULT NULL COMMENT '사용업무  수',
  `TASK_INFO` varchar(1000) DEFAULT NULL COMMENT '사용업무 정보 (인터넷결제, 000결제 등의 정보) - JSON',
  `DOMAIN_INFO` varchar(1000) DEFAULT NULL COMMENT '도매인정보 (IP, PORT 등) - JSON',
  `LICENSE` varchar(2000) DEFAULT NULL COMMENT '라이선스 정보 - JSON',
  `DESCRIPTION` varchar(1000) DEFAULT NULL COMMENT '비고',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '최초등록일자',
  `CREATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최초 등록자',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '최근수정일자',
  `UPDATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최근 수정자',
  PRIMARY KEY (`USE_ORG_CODE`)
) COMMENT='이용기관 정보';

CREATE TABLE `OACX_WORKBOARD` (
  `BOARD_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '게시물 아이디',
  `TITLE` varchar(100) DEFAULT NULL COMMENT '제목',
  `CONTENT` LONGTEXT DEFAULT NULL COMMENT '내용',
  `CREATE_DATE` datetime DEFAULT NULL COMMENT '최근수정일자',
  `CREATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최초 등록자',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '최근수정일자',
  `UPDATE_USER_ID` varchar(16) DEFAULT NULL COMMENT '최근 수정자',
  PRIMARY KEY (`BOARD_ID`)
) COMMENT='게시물 정보';

CREATE TABLE `OACX_TEMP_TOKEN` (
   `TX_ID` varchar(40) NOT NULL COMMENT '결과 요청 tx_id',
   `TOKEN` longtext NOT NULL COMMENT '암호화 토큰',
   `CREATE_DATE` datetime NOT NULL COMMENT '토큰 발급 일시',
   PRIMARY KEY (`TX_ID`)
) COMMENT='임시 토큰 저장';

CREATE TABLE `OACX_MENU` (
    `MENU_ID` varchar(40) NOT NULL COMMENT '메뉴 아이디',
    `MENU_NAME` varchar(40) NOT NULL COMMENT '메뉴명',
    `MENU_URL` varchar(50) NOT NULL COMMENT '메뉴 URL',
    `MENU_PATH` varchar(100) NOT NULL COMMENT '메뉴 경로',
    `MENU_ID_PATH` varchar(100) NOT NULL COMMENT '메뉴 아이디 경로',
    `MENU_AUTH` INT NOT NULL COMMENT '메뉴 권한 (0: 슈퍼관리자, 1: 관리자, 2: 일반운영자)',
    CONSTRAINT OACX_MENU_PK PRIMARY KEY (`MENU_ID`)
) COMMENT='메뉴';

CREATE TABLE `OACX_MENU_ACTION` (
    `MENU_ACTION_URL` varchar(50) NOT NULL COMMENT '행위 URL',
    `MENU_ACTION_METHOD` varchar(7) NOT NULL COMMENT 'HTTP Method',
    `MENU_ACTION_DESC` varchar(50) NOT NULL COMMENT '행위 설명',
    `MENU_ID` varchar(40) NOT NULL COMMENT '메뉴 아이디',
    `MENU_NAME` varchar(40) NOT NULL COMMENT '메뉴명',
    `PROCESS` CHAR(1) NOT NULL COMMENT 'CRUD(C: 등록, R: 조회, U: 수정, D: 삭제)',
    CONSTRAINT OACX_MENU_ACTION_PK PRIMARY KEY (`MENU_ACTION_URL`, `MENU_ACTION_METHOD`)
) COMMENT='메뉴 별 행위';

CREATE TABLE `OACX_LOG` (
    `LOG_ID` INT auto_increment NOT NULL COMMENT '로그 아이디',
    `LOG_DATETIME` DATETIME DEFAULT SYSDATE() NOT NULL COMMENT '로그 시간',
    `ID` varchar(50) NOT NULL COMMENT '사용자 아이디',
    `NAME` varchar(50) NOT NULL COMMENT '사용자명',
    `MENU_NAME` varchar(40) NOT NULL COMMENT '메뉴명',
    `MENU_ACTION_DESC` varchar(50) NOT NULL COMMENT '행위 설명',
    `INPUT_DATA` TEXT NULL COMMENT '등록, 수정 시 입력 데이터(json)',
    `IP` varchar(15) NULL COMMENT '접근 IP',
    CONSTRAINT OACX_LOG_PK PRIMARY KEY (`LOG_ID`)
) COMMENT='감사 로그';