/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+09:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- VC_VERIFIER 데이터베이스 명칭 확인

-- 테이블 VF_ORGANIZATION
CREATE TABLE IF NOT EXISTS `VF_ORGANIZATION` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `PARTNER_CODE` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '이용기관 코드',
    `DOMAIN` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '도메인 또는 명칭',
    `APP_TITLE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MDL 앱에 표시되는 회사명칭',
    `APP_CONTENT` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MDL 앱에 표시되는 회사상세(괄호 안에 값)',
    `VERIFY_HOST` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '검증서버 Host(null인 경우 MDL 검증서버 URL)',
    `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `PARTNER_CODE` (`PARTNER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_AVAILABLE_SERVICE_CODE
CREATE TABLE IF NOT EXISTS `VF_AVAILABLE_SERVICE_CODE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `ORGANIZATION_ID` bigint(20) NOT NULL COMMENT '이용기관 ID',
  `SERVICE_CODE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '서비스 코드',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- 테이블 VF_TRANSACTION_GROUP
CREATE TABLE IF NOT EXISTS `VF_TRANSACTION_GROUP` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
    `TRANSACTION_ID` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '거래코드',
    `PARTNER_CODE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '이용기관 코드',
    `SERVICE_CODE` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '서비스 코드',
    `ENCRYPT_TYPE` INT DEFAULT NULL COMMENT 'VP제출에 사용할 암호화 알고리즘',
    `KEY_TYPE` INT DEFAULT NULL COMMENT 'VP제출에 사용할 키교환 알고리즘',
    `TRANSACTION_MODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '거래 형식 (QR, PUSH, APP 등)',
    `APP_TITLE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MDL 앱에 표시되는 회사명칭',
    `APP_CONTENT` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MDL 앱에 표시되는 회사상세(괄호 안에 값)',
    `VERIFY_HOST` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '검증서버 Host(null인 경우 MDL 검증서버 URL)',
    `NONCE` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '위변조 확인을 위한 nonce 값 저장',
    `EXTERNAL_OPTIONS` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '외부 입력값',
    `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
    `PRESENT_TYPE` INT COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '제출 타입',
    `TEL_NO` INT DEFAULT NULL COMMENT '핸드폰 번호 제출 여부',
    `CI` INT DEFAULT NULL COMMENT 'CI 제출 여부',
    `ZKP_VERIFY_TYPE` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ZKP 검증 종류',
    `OPERATION_MODE`varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '동작 모드(direct/indirect/proxy)',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `TRANSACTION_ID` (`TRANSACTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_ERROR_HISTORY 
CREATE TABLE IF NOT EXISTS `VF_ERROR_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `TRANSACTION_GROUP_ID` bigint(20) DEFAULT NULL COMMENT '거래내역 그룹 ID',
  `ERROR_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '오류코드',
  `ERROR_MESSAGE` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STACK_TRACE` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '오류 스택',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_TEMPORARY_VP 
CREATE TABLE IF NOT EXISTS `VF_TEMPORARY_VP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `TRANSACTION_GROUP_ID` bigint(20) NOT NULL COMMENT '거래내역 그룹 ID',
  `VP_DATA` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '임시 VP 데이터',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_TRANSACTION_HISTORY 
CREATE TABLE IF NOT EXISTS `VF_TRANSACTION_HISTORY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `TRANSACTION_GROUP_ID` bigint(20) NOT NULL COMMENT '거래내역 그룹 ID',
  `M_TYPE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `M_VERSION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `M_CMD` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
  `AUTH_TYPE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '인증 형식 (BIO, PIN, FACE)',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_WHITELIST
CREATE TABLE IF NOT EXISTS `VF_WHITELIST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `ORGANIZATION_ID` bigint(20) NOT NULL COMMENT '이용기관 ID',
  `IP` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '허용 IP',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_SCHEDULE
CREATE TABLE IF NOT EXISTS `VF_SCHEDULE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `SERVER_KEY` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '서버 키',
  `DB_STATUS` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'DB 유휴 상태',
  `JOB_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '작업 명',
  `UPDATED_AT` datetime DEFAULT NULL COMMENT 'Lock 변경 시간',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SERVER_KEY` (`SERVER_KEY`),
  UNIQUE KEY `UK_JOB_LOCK` (`JOB_NAME`, `DB_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_ZKP
CREATE TABLE IF NOT EXISTS `VF_ZKP` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `VERIFY_TYPE` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '검증 종류',
  `SCHEMA_NAME` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '스키마 네임',
  `ATTRIBUTES` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Attributes 값',
  `PREDICATES` VARCHAR(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Predicates 값',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '생성일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_CA_APP_LIST
CREATE TABLE IF NOT EXISTS `VF_CA_APP_LIST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `APP_CODE` VARCHAR(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '앱 코드',
  `APP_NAME` VARCHAR(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '앱 명칭',
  `APP_ICON` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '앱 아이콘 BI',
  `CA_PUSH_URL` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '앱 PUSH 서버 도메인',
  `CA_DID` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'CA DID',
  `CA_PUB_KEY` VARCHAR(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'CA PubKey',
  `APP_LINK_AOS` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AOS Scheme',
  `APP_LINK2_AOS` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AOS Scheme2',
  `APP_LINK_IOS` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IOS Scheme',
  `APP_LINK2_IOS` VARCHAR(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'IOS Scheme2',
  `USE_CALLBACK_YN` VARCHAR(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CA_SERVER_CALLBACK_URL` VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `APP_CODE` (`APP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 테이블 VF_SHEDLOCK
CREATE TABLE VF_SHEDLOCK (
  `NAME` VARCHAR(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Job 명칭',
  `LOCK_UNTIL` datetime NOT NULL COMMENT 'LOCK 유지 시간',
  `LOCKED_AT` datetime NOT NULL COMMENT 'LOCK 시작 시간',
  `LOCKED_BY` VARCHAR(255) NOT NULL COMMENT 'LOCK을 획득한 호스트',
  PRIMARY KEY (`NAME`)
);

CREATE TABLE IF NOT EXISTS `VF_SCHEDULER_EXEC_HISTORY` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `JOB_NAME` VARCHAR(50) DEFAULT NULL COMMENT '스케줄러 작업 명칭',
  `SERVER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '실행 서버 호스트 명칭',
  `EXEC_TIME` datetime DEFAULT NULL COMMENT '작업 시간',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DB 조회 성능 향상 필요 시 생성
--CREATE INDEX IDX_VF_TG_CRT_AT ON `VF_TRANSACTION_GROUP` (`CREATED_AT`);
--CREATE INDEX IDX_VF_TH_CRT_AT ON `VF_TRANSACTION_HISTORY` (`CREATED_AT`);
--CREATE INDEX IDX_VF_EH_CRT_AT ON `VF_ERROR_HISTORY` (`CREATED_AT`);
--CREATE INDEX IDX_VF_TEMPORARY_VP_CREATED_AT ON `VF_TEMPORARY_VP` (`CREATED_AT`);


/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;