----------------------------------------------------------
-- 초기 데이터 로딩
----------------------------------------------------------


-- admin / 1q2w3e4r5t!@ 초기 설정
INSERT INTO OACX_ADMIN (ID,NAME,PASSWD,SEED,PASSWD_CHANGE_DATE,STATE_CODE,AUTHORITY_CODE,DEPT_NAME,PHONE_NO,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID) VALUES
('admin','관리자','RFg55eq7gRBBW5PHMFNQg9pWXs3bLwhHNC1aRbNNiis=','1192658319',NULL,'Y','0','관리자','070-8240-6935','2021-03-16 09:08:19','','2021-03-16 09:08:19',NULL);
	
-- 인증사 목록 insert
INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cokakao_v1.5','cokakao','카카오지갑',NULL,'https://cert-sign.kakao.com','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',null,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('copass_v1.5','copass','통신사패스',NULL,'https://pub-api.passauth.co.kr','ent','__OPER_SORT__','y',NULL,NULL,'',NULL,'AUTH,SIGN',null,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('conaver_v1.5','conaver','네이버',NULL,'https://nsign-gw.naver.com','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',null,'admin',NULL,NULL,'v1.5');

-- 토스 직연동(한국전자인증 주관 토스와 혼동할 수 있으니 둘 중에 하나만 사용하는 것을 권고
INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cotoss_v1.5','cotoss','토스(직)',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cobanksalad_v1.5','cobanksalad','뱅크샐러드',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,NULL,NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('coshinhan_v1.5','coshinhan','신한인증서',NULL,'https://ca.shinhan.com/','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cokica_v1.5','cokica','삼성패스',NULL,'https://ses.signgate.com','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cokb_v1.5','cokb','KB은행',NULL,'https://openapi.kbstar.com:8443','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cowoori_v1.5','cowoori','우리은행',NULL,'https://openapi.kbstar.com:8443','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cohana_v1.5','cohana','하나은행',NULL,'https://openapi.kbstar.com:8443','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('conh_v1.5','conh','농협은행',NULL,'https://openapi.kbstar.com:8443','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('coibk_v1.5', 'coibk', 'IBK인증서', NULL, NULL, 'ent', '__OPER_SORT__', 'y', NULL, NULL, NULL, NULL, 'AUTH,SIGN', NULL, NULL, NULL, '', 'v1.5');

-- 본인확인 서비스 insert
INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cohana-identify_v1.5','cohana-identify','하나인증서본인확인',NULL,'https://apis.hanafnapimarket.com','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'IDENT',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cokb-identify_v1.5','cokb-identify','국민본인확인',NULL,'https://openapi.kbstar.com:8443','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'IDENT',NULL,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('coshinhan-identify_v1.5','coshinhan-identify','신한인증서본인확인',NULL,'https://ca.shinhan.com/','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'IDENT',null,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cotoss-identify_v1.5','cotoss-identify','토스본인확인',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'IDENT',null,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cowoori-identify_v1.5','cowoori-identify','우리은행본인확인',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'IDENT',NULL,'admin',NULL,NULL,'v1.5');


--참고, Deprecated Service
INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cokakaopay_v1.5','cokakaopay','카카오페이',NULL,'https://gw-cert.kakao.com','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',null,'admin',NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('copayco_v1.5','copayco','페이코',NULL,'https://ca.payco.com','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',null,'admin',NULL,NULL,'v1.5');
-- 한국전자인증 중계 토스
INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('cotoss-esign_v1.5','cotoss-esign','토스',NULL,'https://certtoss.crosscert.com:8080','ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'AUTH,SIGN',null,'admin',NULL,NULL,'v1.5');


--VC Verifier Insert
INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('coidentitydocument','coidentitydocument','모바일신분증',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'MID',NULL,NULL,NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('comdl_v1.5','comdl','모바일운전면허증',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'MID,AUTH',NULL,NULL,NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('comrc_v1.5','comrc','모바일주민등록증',NULL,NULL,'ent','__OPER_SORT__','y',NULL,NULL,NULL,NULL,'MID',NULL,NULL,NULL,NULL,'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('comnh_v1.5', 'comnh', '모바일유공자증', NULL, NULL, 'ent', '__OPER_SORT__', 'y', NULL, NULL, NULL, NULL, 'MID', NULL, NULL, NULL, NULL, 'v1.5');

INSERT INTO OACX_PROVIDER (ID,PROVIDER_ID,NAME,CONFIG,URL,PROVIDER_TYPE,OPER_SORT,STATUS_CODE,UNUSE_STYLE,DESCRIPTION,PROVIDER_IF,PROVIDER_IF2,SERVICE_TYPE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,VERSION) VALUES
('coresidence_v1.5', 'coresidence', '모바일외국인등록증', NULL, NULL, 'ent', '__OPER_SORT__', 'y', NULL, NULL, NULL, NULL, 'MID', NULL, NULL, NULL, NULL, 'v1.5');

INSERT INTO OACX_PROVIDER(ID, PROVIDER_ID, NAME, CONFIG, URL, PROVIDER_TYPE, OPER_SORT, STATUS_CODE, UNUSE_STYLE, DESCRIPTION, PROVIDER_IF, PROVIDER_IF2, SERVICE_TYPE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID, VERSION)
VALUES('cosspay_v1.5', 'cosspay', '삼성월렛', NULL, NULL, 'ent', '__OPER_SORT__', 'y', NULL, NULL, NULL, NULL, 'MID', NULL, NULL, NULL, NULL, 'v1.5');

INSERT INTO OACX_PROVIDER
(ID, PROVIDER_ID, NAME, CONFIG, URL, PROVIDER_TYPE, OPER_SORT, STATUS_CODE, UNUSE_STYLE, DESCRIPTION, PROVIDER_IF, PROVIDER_IF2, SERVICE_TYPE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID, VERSION)
VALUES('comdc', 'comdc', '모바일장애인증', NULL, NULL, 'ent', '__OPER_SORT__', 'y', NULL, NULL, NULL, NULL, 'MID', NULL, NULL, '2024-08-23 10:26:33.000', NULL, 'v1.5');
INSERT INTO OACX_PROVIDER
(ID, PROVIDER_ID, NAME, CONFIG, URL, PROVIDER_TYPE, OPER_SORT, STATUS_CODE, UNUSE_STYLE, DESCRIPTION, PROVIDER_IF, PROVIDER_IF2, SERVICE_TYPE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID, VERSION)
VALUES('govid', 'govid', '모바일공무원증', NULL, NULL, 'ent', '__OPER_SORT__', 'y', NULL, NULL, NULL, NULL, 'MID', NULL, NULL, '2024-08-23 10:26:33.000', NULL, 'v1.5');

-- 메뉴 데이터 추가
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0010', '시스템 관리', '/page/admin', '/src/html/admin/admin.html', '0010;', 2);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0011', '서비스 관리', '/page/service', '/src/html/service/service.html', '0010;0011;', 1);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0012', '사용자 관리', '/page/admin', '/src/html/admin/admin.html', '0010;0012;', 2);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0013', '로그 관리', '/page/log', '/src/html/log/log.html', '0010;0013;', 1);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0014', '워크보드', '/page/admin/storyboard', '/src/html/admin/storyboard.html', '0010;0014;', 1);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0015', '요청 제한 IP 관리', '/page/limitIp', '/src/html/limitIp/limitIp.html', '0015;', 1);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0020', '거래 조회', '/page/authenticate', '/src/html/authenticate/authenticate.html', '0020;', 2);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0021', '인증기관별 거래 조회', '/page/authenticate', '/src/html/authenticate/authenticate.html', '0020;0021;', 2);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0030', '통계 관리', '/page/statistics', '/src/html/statistics/statistics.html', '0030;', 2);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0031', '통계 관리', '/page/statistics', '/src/html/statistics/statistics.html', '0030;0031;', 2);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0040', '인증기관 설정', '/page/provider', '/src/html/provider/provider.html', '0040;', 1);
INSERT INTO OACX_MENU (MENU_ID, MENU_NAME, MENU_URL, MENU_PATH, MENU_ID_PATH, MENU_AUTH)
VALUES('0041', '인증기관 관리', '/page/provider', '/src/html/provider/provider.html', '0040;0041;', 1);

-- 메뉴 별 행위 데이터 추가
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/admin', 'POST', '사용자 등록', '0012', '사용자 관리', 'C');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/admin', 'DELETE', '사용자 삭제', '0012', '사용자 관리', 'D');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/admin', 'PUT', '사용자 수정', '0012', '사용자 관리', 'U');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/admin/paging/search', 'POST', '사용자 목록 조회', '0012', '사용자 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/authenticate/search', 'POST', '인증 목록 조회', '0021', '인증기관별 거래 조회', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/init', 'PUT', '비밀번호 초기화', '0012', '사용자 관리', 'U');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/log/paging/search', 'POST', '로그 목록 조회', '0013', '로그 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/login', 'POST', '로그인', '0000', '로그인 페이지', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/login/lock', 'GET', '계정 잠김', '0000', '로그인 페이지', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/logout', 'GET', '로그아웃', '0000', '로그인 페이지', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/logout/jwt', 'GET', '토큰 만료 로그아웃', '0000', '로그인 페이지', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/logout/duplicate', 'GET', '중복 접속 로그아웃', '0000', '로그인 페이지', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/provider', 'DELETE', '인증기관 정보 삭제', '0041', '인증기관 관리', 'D');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/provider', 'PUT', '인증기관 정보 수정', '0041', '인증기관 관리', 'U');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/provider/search', 'GET', '인증기관 정보 조회', '0041', '인증기관 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/pw', 'PUT', '초기 비밀번호 변경', '0000', '로그인 페이지', 'U');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/service', 'POST', '서비스 등록', '0011', '서비스 관리', 'C');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/service', 'DELETE', '서비스 삭제', '0011', '서비스 관리', 'D');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/service', 'PUT', '서비스 수정', '0011', '서비스 관리', 'U');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/service/paging/search', 'POST', '서비스 목록 조회', '0011', '서비스 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/total-cnt-by/day', 'POST', '통계 목록 조회(일자별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/total-cnt-by/month', 'POST', '통계 목록 조회(월별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/total-cnt-by/quarter', 'POST', '통계 목록 조회(분기별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/total-cnt-by/week', 'POST', '통계 목록 조회(주간별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/workboard', 'POST', '워크보드 등록', '0014', '워크보드', 'C');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/workboard', 'DELETE', '워크보드 삭제', '0014', '워크보드', 'D');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/workboard', 'PUT', '워크보드 수정', '0014', '워크보드', 'U');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/workboard/paging/search', 'POST', '워크보드 목록 조회', '0014', '워크보드', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/excel/day', 'POST', '통계 목록 엑셀 다운로드(일자별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/excel/month', 'POST', '통계 목록 엑셀 다운로드(월별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/excel/quarter', 'POST', '통계 목록 엑셀 다운로드(분기별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/statistics/excel/week', 'POST', '통계 목록 엑셀 다운로드(주간별)', '0031', '통계 관리', 'R');
INSERT INTO OACX_MENU_ACTION(MENU_ACTION_URL, MENU_ACTION_METHOD, MENU_ACTION_DESC, MENU_ID, MENU_NAME, PROCESS)
VALUES('/admin/limitIp/paging/search', 'POST', '요청 제한 IP 목록 조회', '0015', '요청 제한 IP 관리', 'R');